name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  mymagic:
    runs-on: ubuntu-latest
    container: 
      image: oryd/xgoreleaser:1.14.4-0.138.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      volumes: 
        - /home/runner/work/kratos/kratos:/go
      options:
        - --entrypoint /bin/bash
    steps:
      - run: release --config .goreleaser_simple.yml --skip-publish