name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  mymagic: 
    container: 
      image: oryd/xgoreleaser:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      volumes: 
        - "/home/runner/work/_temp/_github_home":"/go"
    steps:
    - run: release --skip-publish